[project]
name = "playing-with-quicksilver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nikola[extras]>=8.3.1",
]
